FROM golang:1.21-alpine as builder

RUN apk update && apk add --no-cache git ca-certificates tzdata && update-ca-certificates

ENV PROJECT_ID=
ENV PUBSUB_TOPIC=
ENV BUCKET_NAME=
ENV DB_URL=

WORKDIR $GOPATH/src/revo-voting

COPY . .

RUN echo $PWD && ls -la

RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -a -installsuffix cgo -o /go/bin/revo-app .

# Stage 2
FROM alpine:3.17

RUN apk update

# Import from builder.
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd

# Copy the executable.
COPY --from=builder /go/bin/revo-app /go/bin/revo-app

ENTRYPOINT ["/go/bin/revo-app"]