// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote-status-service

package com.revo.application.gRPC.protogen;

/**
 * Protobuf type {@code com.revo.application.gRPC.protogen.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.revo.application.gRPC.protogen.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    voteId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            voteId_ = s;
            break;
          }
          case 16: {

            candidatePosition_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.revo.application.gRPC.protogen.VoteStatusServiceOuterClass.internal_static_com_revo_application_gRPC_protogen_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.revo.application.gRPC.protogen.VoteStatusServiceOuterClass.internal_static_com_revo_application_gRPC_protogen_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.revo.application.gRPC.protogen.Request.class, com.revo.application.gRPC.protogen.Request.Builder.class);
  }

  public static final int VOTE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object voteId_;
  /**
   * <code>string vote_id = 1;</code>
   * @return The voteId.
   */
  @java.lang.Override
  public java.lang.String getVoteId() {
    java.lang.Object ref = voteId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voteId_ = s;
      return s;
    }
  }
  /**
   * <code>string vote_id = 1;</code>
   * @return The bytes for voteId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVoteIdBytes() {
    java.lang.Object ref = voteId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voteId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_POSITION_FIELD_NUMBER = 2;
  private int candidatePosition_;
  /**
   * <code>int32 candidate_position = 2;</code>
   * @return The candidatePosition.
   */
  @java.lang.Override
  public int getCandidatePosition() {
    return candidatePosition_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voteId_);
    }
    if (candidatePosition_ != 0) {
      output.writeInt32(2, candidatePosition_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(voteId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voteId_);
    }
    if (candidatePosition_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, candidatePosition_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.revo.application.gRPC.protogen.Request)) {
      return super.equals(obj);
    }
    com.revo.application.gRPC.protogen.Request other = (com.revo.application.gRPC.protogen.Request) obj;

    if (!getVoteId()
        .equals(other.getVoteId())) return false;
    if (getCandidatePosition()
        != other.getCandidatePosition()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VOTE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getVoteId().hashCode();
    hash = (37 * hash) + CANDIDATE_POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getCandidatePosition();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.revo.application.gRPC.protogen.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.revo.application.gRPC.protogen.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.revo.application.gRPC.protogen.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.revo.application.gRPC.protogen.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.revo.application.gRPC.protogen.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.revo.application.gRPC.protogen.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.revo.application.gRPC.protogen.Request)
      com.revo.application.gRPC.protogen.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.revo.application.gRPC.protogen.VoteStatusServiceOuterClass.internal_static_com_revo_application_gRPC_protogen_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.revo.application.gRPC.protogen.VoteStatusServiceOuterClass.internal_static_com_revo_application_gRPC_protogen_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.revo.application.gRPC.protogen.Request.class, com.revo.application.gRPC.protogen.Request.Builder.class);
    }

    // Construct using com.revo.application.gRPC.protogen.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      voteId_ = "";

      candidatePosition_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.revo.application.gRPC.protogen.VoteStatusServiceOuterClass.internal_static_com_revo_application_gRPC_protogen_Request_descriptor;
    }

    @java.lang.Override
    public com.revo.application.gRPC.protogen.Request getDefaultInstanceForType() {
      return com.revo.application.gRPC.protogen.Request.getDefaultInstance();
    }

    @java.lang.Override
    public com.revo.application.gRPC.protogen.Request build() {
      com.revo.application.gRPC.protogen.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.revo.application.gRPC.protogen.Request buildPartial() {
      com.revo.application.gRPC.protogen.Request result = new com.revo.application.gRPC.protogen.Request(this);
      result.voteId_ = voteId_;
      result.candidatePosition_ = candidatePosition_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.revo.application.gRPC.protogen.Request) {
        return mergeFrom((com.revo.application.gRPC.protogen.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.revo.application.gRPC.protogen.Request other) {
      if (other == com.revo.application.gRPC.protogen.Request.getDefaultInstance()) return this;
      if (!other.getVoteId().isEmpty()) {
        voteId_ = other.voteId_;
        onChanged();
      }
      if (other.getCandidatePosition() != 0) {
        setCandidatePosition(other.getCandidatePosition());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.revo.application.gRPC.protogen.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.revo.application.gRPC.protogen.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object voteId_ = "";
    /**
     * <code>string vote_id = 1;</code>
     * @return The voteId.
     */
    public java.lang.String getVoteId() {
      java.lang.Object ref = voteId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voteId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string vote_id = 1;</code>
     * @return The bytes for voteId.
     */
    public com.google.protobuf.ByteString
        getVoteIdBytes() {
      java.lang.Object ref = voteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string vote_id = 1;</code>
     * @param value The voteId to set.
     * @return This builder for chaining.
     */
    public Builder setVoteId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voteId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string vote_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoteId() {
      
      voteId_ = getDefaultInstance().getVoteId();
      onChanged();
      return this;
    }
    /**
     * <code>string vote_id = 1;</code>
     * @param value The bytes for voteId to set.
     * @return This builder for chaining.
     */
    public Builder setVoteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      voteId_ = value;
      onChanged();
      return this;
    }

    private int candidatePosition_ ;
    /**
     * <code>int32 candidate_position = 2;</code>
     * @return The candidatePosition.
     */
    @java.lang.Override
    public int getCandidatePosition() {
      return candidatePosition_;
    }
    /**
     * <code>int32 candidate_position = 2;</code>
     * @param value The candidatePosition to set.
     * @return This builder for chaining.
     */
    public Builder setCandidatePosition(int value) {
      
      candidatePosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 candidate_position = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidatePosition() {
      
      candidatePosition_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.revo.application.gRPC.protogen.Request)
  }

  // @@protoc_insertion_point(class_scope:com.revo.application.gRPC.protogen.Request)
  private static final com.revo.application.gRPC.protogen.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.revo.application.gRPC.protogen.Request();
  }

  public static com.revo.application.gRPC.protogen.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.revo.application.gRPC.protogen.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

