// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote-status-service

package com.revo.application.gRPC.protogen;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.revo.application.gRPC.protogen.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string imgLink = 4;</code>
   * @return The imgLink.
   */
  java.lang.String getImgLink();
  /**
   * <code>string imgLink = 4;</code>
   * @return The bytes for imgLink.
   */
  com.google.protobuf.ByteString
      getImgLinkBytes();
}
