// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote-status-service

package com.revo.application.gRPC.protogen;

public final class VoteStatusServiceOuterClass {
  private VoteStatusServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_revo_application_gRPC_protogen_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_revo_application_gRPC_protogen_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_revo_application_gRPC_protogen_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_revo_application_gRPC_protogen_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023vote-status-service\022\"com.revo.applicat" +
      "ion.gRPC.protogen\"6\n\007Request\022\017\n\007vote_id\030" +
      "\001 \001(\t\022\032\n\022candidate_position\030\002 \001(\005\"N\n\010Res" +
      "ponse\022\016\n\006status\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013d" +
      "escription\030\003 \001(\t\022\017\n\007imgLink\030\004 \001(\t2}\n\021Vot" +
      "eStatusService\022h\n\013CheckStatus\022+.com.revo" +
      ".application.gRPC.protogen.Request\032,.com" +
      ".revo.application.gRPC.protogen.Response" +
      "B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_revo_application_gRPC_protogen_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_revo_application_gRPC_protogen_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_revo_application_gRPC_protogen_Request_descriptor,
        new java.lang.String[] { "VoteId", "CandidatePosition", });
    internal_static_com_revo_application_gRPC_protogen_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_revo_application_gRPC_protogen_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_revo_application_gRPC_protogen_Response_descriptor,
        new java.lang.String[] { "Status", "Name", "Description", "ImgLink", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
