name: Create Voting

on:
  push:
    branches: [ main ]
    paths:
      - 'create-voting/**'
  pull_request:
    branches: [ main ] 
    paths:
      - 'create-voting/**' 

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: go mod tidy

      - name: Go Test
        run: go test -v -failfast -race ./...

      - name: Go Build
        run: go build -v ./...